name: Deployment

on: 
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Confirgure Node
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'
          
      - name: Install Product Dependencies
        run: npm install react-scripts --save
        
      - name: Build Project
        run: npm run build
        
      - name: copy file via ssh key
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.KEY }}
          source: "build/*"
          target: "/var/apps/baseball-app"  
          overwrite: true
      
