name: Deployment

on: 
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Confirgure Node
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'
          
      - name: Install Product Dependencies
        run: npm install react-scripts --save
        
      - name: Build Project
        run: npm run build
          
      
